# Generated by Django 3.2 on 2021-04-19 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_auto_20210416_0405'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ('created',)},
        ),
    ]
